import fs from 'node:fs/promises'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'

const exec = promisify(execFile)
const SYMBOLS = (process.env.SYMBOLS ?? 'BTCUSDT,ETHUSDT,SOLUSDT,XRPUSDT').split(',').map(s => s.trim()).filter(Boolean)
const INTERVAL = '15m'
const MONTHS = Number(process.env.MONTHS ?? 36)
const FEE_BPS = Number(process.env.FEE_BPS ?? 10)
const SLIPPAGE_BPS = Number(process.env.SLIPPAGE_BPS ?? 5)
const END = process.env.END ? new Date(process.env.END) : new Date()
const START = process.env.START ? new Date(process.env.START) : new Date(END.getTime() - MONTHS * 30.4375 * 86400000)
const DATA_DIR = path.join(process.cwd(), '.backtest-cache')
const OUT_DIR = path.join(process.cwd(), 'backtest-results')

const clamp = (v, min = 0, max = 100) => Math.min(max, Math.max(min, v))
const between = (v, lo, hi) => Number.isFinite(v) && v >= lo && v <= hi
const valid = n => n !== null && Number.isFinite(n)

function sma(values, period) { if (values.length < period) return null; const a = values.slice(-period); return a.reduce((x,y)=>x+y,0)/period }
function ema(values, period) { if (values.length < period) return null; let r = values.slice(0,period).reduce((x,y)=>x+y,0)/period; const k=2/(period+1); for(let i=period;i<values.length;i++) r=values[i]*k+r*(1-k); return r }
function ret(candles, bars) { if(candles.length<=bars) return null; const a=candles[candles.length-1].close,b=candles[candles.length-1-bars].close; return b>0?a/b-1:null }
function rsi(values, period) { if(values.length<=period)return null; let g=0,l=0; for(let i=1;i<=period;i++){const d=values[i]-values[i-1];if(d>=0)g+=d;else l-=d} let ag=g/period,al=l/period; for(let i=period+1;i<values.length;i++){const d=values[i]-values[i-1];ag=(ag*(period-1)+Math.max(d,0))/period;al=(al*(period-1)+Math.max(-d,0))/period} if(al===0)return 100; return 100-100/(1+ag/al) }
function atr(candles, period){if(candles.length<=period)return null;const trs=[];for(let i=1;i<candles.length;i++){const c=candles[i],p=candles[i-1].close;trs.push(Math.max(c.high-c.low,Math.abs(c.high-p),Math.abs(c.low-p)))}return sma(trs,period)}
function features(candles){const closes=candles.map(c=>c.close),vols=candles.map(c=>c.volume),last=candles.at(-1);const e20=ema(closes,20),e50=ema(closes,50),e200=ema(closes,200);const vs=sma(vols,20);const e12=ema(closes,12),e26=ema(closes,26);const macd=valid(e12)&&valid(e26)?e12-e26:null;const ms=[];if(closes.length>=35)for(let i=26;i<=closes.length;i++){const f=ema(closes.slice(0,i),12),s=ema(closes.slice(0,i),26);if(valid(f)&&valid(s))ms.push(f-s)}const msig=ms.length>=9?ema(ms,9):null;return{r15:ret(candles,1),r1h:ret(candles,4),r4h:ret(candles,16),r24:ret(candles,96),e20,e50,e200,trend:valid(e20)&&valid(e50)&&e50!==0?e20/e50-1:null,rsi:rsi(closes,14),macdHist:valid(macd)&&valid(msig)?macd-msig:null,vr:valid(vs)&&vs>0?last.volume/vs:null,atr:atr(candles,14)}}
function score(f){let s=50;if(f.e200!==null){if(f.e20!==null&&f.e50!==null)s+=f.e20>f.e50?8:-8;if(f.trend!==null){if(f.trend>=.01)s+=10;else if(f.trend>=.003)s+=5;else if(f.trend<=-.01)s-=10;else if(f.trend<=-.003)s-=5}}if(f.r15!==null)s+=clamp(f.r15*1000,-5,5);if(f.r1h!==null)s+=clamp(f.r1h*400,-8,8);if(f.r4h!==null)s+=clamp(f.r4h*150,-6,6);if(f.r24!==null)s+=clamp(f.r24*50,-6,6);if(f.vr!==null){if(f.vr>=2)s+=10;else if(f.vr>=1.3)s+=7;else if(f.vr>=1.05)s+=3;else if(f.vr<.7)s-=6}if(f.macdHist!==null)s+=f.macdHist>0?5:-5;if(f.rsi!==null){if(between(f.rsi,52,68))s+=5;else if(between(f.rsi,45,52)||between(f.rsi,68,72))s+=1;else if(f.rsi>78)s-=6;else if(f.rsi<35)s-=5}if(f.atr!==null&&f.e200!==null&&f.atr/f.e200>.08)s-=5;const n=Math.round(clamp(s));return{score:n,long:n>=75}}

function months(start,end){const a=[];const d=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),1)),z=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),1));while(d<=z){a.push(`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`);d.setUTCMonth(d.getUTCMonth()+1)}return a}
async function getMonth(symbol,month){const zip=path.join(DATA_DIR,`${symbol}-${month}.zip`);try{await fs.access(zip)}catch{const u=`https://data.binance.vision/data/spot/monthly/klines/${symbol}/${INTERVAL}/${symbol}-${INTERVAL}-${month}.zip`;const r=await fetch(u);if(!r.ok)throw new Error(`download ${r.status} ${u}`);await fs.mkdir(DATA_DIR,{recursive:true});await fs.writeFile(zip,Buffer.from(await r.arrayBuffer()))}const dir=path.join(DATA_DIR,`${symbol}-${month}`);await fs.mkdir(dir,{recursive:true});await exec('unzip',['-oq',zip,'-d',dir]);const f=(await fs.readdir(dir)).find(x=>x.endsWith('.csv'));const text=await fs.readFile(path.join(dir,f),'utf8');return text.trim().split(/\r?\n/).slice(text.split(/\r?\n/)[0].toLowerCase().includes('open time')?1:0).map(line=>{const p=line.split(',');return{openTime:+p[0],open:+p[1],high:+p[2],low:+p[3],close:+p[4],volume:+p[5]}}).filter(c=>Object.values(c).every(Number.isFinite))}
async function load(symbol){let c=[];for(const m of months(START,END))c.push(...await getMonth(symbol,m));const min=START.getTime()-200*15*60000;return c.filter(x=>x.openTime>=min&&x.openTime<=END.getTime()).sort((a,b)=>a.openTime-b.openTime)}
function summary(trades,h){const v=trades.map(t=>t.net[h]).filter(Number.isFinite),wins=v.filter(x=>x>0).length;return{trades:v.length,wins,losses:v.filter(x=>x<0).length,winRate:v.length?wins/v.length:0,avgReturn:v.length?v.reduce((a,b)=>a+b,0)/v.length:0,totalSimpleReturn:v.reduce((a,b)=>a+b,0)}}
async function main(){const trades=[];for(const symbol of SYMBOLS){console.log(`Loading ${symbol}...`);const c=await load(symbol);console.log(`${symbol}: ${c.length} candles`);for(let i=200;i<c.length-16;i++){if(c[i].openTime<START.getTime())continue;const f=features(c.slice(0,i+1)),sig=score(f);if(!sig.long)continue;const raw={'15m':(c[i+1].close-c[i].close)/c[i].close,'1h':(c[i+4].close-c[i].close)/c[i].close,'4h':(c[i+16].close-c[i].close)/c[i].close};const cost=(FEE_BPS+SLIPPAGE_BPS)/10000;const net={};for(const h of Object.keys(raw))net[h]=raw[h]-cost;trades.push({symbol,time:new Date(c[i].openTime).toISOString(),score:sig.score,entry:c[i].close,raw,net})}}
const span=END-START;const cuts={development:new Date(START.getTime()+span*.6666667),validation:new Date(START.getTime()+span*.8333333)};const split=t=>t==='development'?trades.filter(x=>new Date(x.time)<cuts.development):t==='validation'?trades.filter(x=>new Date(x.time)>=cuts.development&&new Date(x.time)<cuts.validation):trades.filter(x=>new Date(x.time)>=cuts.validation);const report={generatedAt:new Date().toISOString(),method:'Exact production score logic, 15m close-to-close, no lookahead, fee+slippage deducted from every trade.',start:START.toISOString(),end:END.toISOString(),symbols:SYMBOLS,feeBps:FEE_BPS,slippageBps:SLIPPAGE_BPS,totalSignals:trades.length,overall:Object.fromEntries(['15m','1h','4h'].map(h=>[h,summary(trades,h)])),splits:Object.fromEntries(['development','validation','out_of_sample'].map(x=>[x,Object.fromEntries(['15m','1h','4h'].map(h=>[h,summary(split(x),h)]))]))};await fs.mkdir(OUT_DIR,{recursive:true});await fs.writeFile(path.join(OUT_DIR,'report.json'),JSON.stringify(report,null,2));await fs.writeFile(path.join(OUT_DIR,'trades.json'),JSON.stringify(trades,null,2));console.log(JSON.stringify(report,null,2))}
main().catch(e=>{console.error(e);process.exit(1)})
