import fs from 'node:fs/promises'
import path from 'node:path'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
const exec = promisify(execFile)
type Candle={openTime:number;open:number;high:number;low:number;close:number;volume:number}
const SYMBOLS=(process.env.SYMBOLS??'BTCUSDT,ETHUSDT,SOLUSDT,XRPUSDT').split(',').map(s=>s.trim()).filter(Boolean)
const MONTHS=Math.max(6,Number(process.env.MONTHS??24)), INTERVAL='1h'
const DATA_DIR=path.join(process.cwd(),'.backtest-cache-discovery'), REPORT_DIR=path.join(process.cwd(),'reports')
const COST=(10+5)/10000
function monthKeys(a:Date,b:Date){const out:string[]=[];const d=new Date(Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),1));const e=new Date(Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),1));while(d<=e){out.push(d.getUTCFullYear()+'-'+String(d.getUTCMonth()+1).padStart(2,'0'));d.setUTCMonth(d.getUTCMonth()+1)}return out}
async function download(symbol:string,m:string){const file=path.join(DATA_DIR,symbol+'-'+INTERVAL+'-'+m+'.zip');try{await fs.access(file);return file}catch{};const url='https://data.binance.vision/data/spot/monthly/klines/'+symbol+'/'+INTERVAL+'/'+symbol+'-'+INTERVAL+'-'+m+'.zip';const res=await fetch(url);if(res.status===404){console.warn('[discovery] 404 '+symbol+' '+m);return null}if(!res.ok)throw new Error('Binance archive '+res.status+': '+url);await fs.mkdir(DATA_DIR,{recursive:true});await fs.writeFile(file,Buffer.from(await res.arrayBuffer()));return file}
async function unzip(file:string){const dir=path.join(DATA_DIR,'tmp-'+Date.now()+'-'+Math.random().toString(36).slice(2));await fs.mkdir(dir,{recursive:true});await exec('unzip',['-oq',file,'-d',dir]);const name=(await fs.readdir(dir)).find(x=>x.endsWith('.csv'));if(!name)throw new Error('No CSV in '+file);const lines=(await fs.readFile(path.join(dir,name),'utf8')).trim().split(/\r?\n/);const start=lines[0]?.toLowerCase().includes('open time')?1:0;const out:Candle[]=[];for(let i=start;i<lines.length;i++){const r=lines[i].split(',');if(r.length<6)continue;const [t,o,h,l,c,v]=r.slice(0,6).map(Number);if([t,o,h,l,c,v].every(Number.isFinite))out.push({openTime:t,open:o,high:h,low:l,close:c,volume:v})}await fs.rm(dir,{recursive:true,force:true});return out}
async function load(symbol:string,start:number,end:number){const out:Candle[]=[];for(const m of monthKeys(new Date(start),new Date(end))){const f=await download(symbol,m);if(f)out.push(...await unzip(f))}return out.filter(c=>c.openTime>=start&&c.openTime<=end).sort((a,b)=>a.openTime-b.openTime)}
function sma(a:number[],n:number){return a.length<n?null:a.slice(-n).reduce((x,y)=>x+y,0)/n}
function ema(a:number[],n:number){if(a.length<n)return null;let x=a.slice(0,n).reduce((p,q)=>p+q,0)/n,k=2/(n+1);for(let i=n;i<a.length;i++)x=a[i]*k+x*(1-k);return x}
function rsi(a:number[],n=14){if(a.length<=n)return null;let g=0,l=0;for(let i=1;i<=n;i++){const d=a[i]-a[i-1];if(d>=0)g+=d;else l-=d}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){const d=a[i]-a[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}if(al===0)return ag===0?50:100;return 100-100/(1+ag/al)}
function atr(c:Candle[],n=14){if(c.length<=n)return null;const x:number[]=[];for(let i=1;i<c.length;i++)x.push(Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close)));return sma(x,n)}
function ret(a:number[],n:number){if(a.length<=n)return null;const b=a[a.length-1-n];return b>0?a[a.length-1]/b-1:null}
function realizedVol(a:number[],n=20){if(a.length<=n)return null;const r:number[]=[];for(let i=1;i<a.length;i++)if(a[i-1]>0&&a[i]>0)r.push(Math.log(a[i]/a[i-1]));if(r.length<n)return null;const x=r.slice(-n),m=x.reduce((p,q)=>p+q,0)/n;return Math.sqrt(x.reduce((p,q)=>p+(q-m)**2,0)/n)*Math.sqrt(n)}
function features(c:Candle[]){const a=c.map(x=>x.close),v=c.map(x=>x.volume),last=c[c.length-1],e20=ema(a,20),e50=ema(a,50),e200=ema(a,200),e12=ema(a,12),e26=ema(a,26);const macd=e12!==null&&e26!==null?e12-e26:null;const ms:number[]=[];for(let i=26;i<=a.length;i++){const x=ema(a.slice(0,i),12),y=ema(a.slice(0,i),26);if(x!==null&&y!==null)ms.push(x-y)}const sig=ms.length>=9?ema(ms,9):null;const vs=sma(v,20);return{e20,e50,e200,trend:e20!==null&&e50!==null?e20/e50-1:null,rsi:rsi(a),macdHist:macd!==null&&sig!==null?macd-sig:null,volumeRatio:vs!==null&&vs>0?last.volume/vs:null,atr:atr(c),vol:realizedVol(a)}}
// Research candidate only: same indicator families as production, normalized to 1h horizons. Never imported by live code.
function score(f:ReturnType<typeof features>,c:Candle[]){let s=50;if(f.e20!==null&&f.e50!==null)s+=f.e20>f.e50?8:-8;if(f.trend!==null)s+=f.trend>=.01?10:f.trend>=.003?5:f.trend<=-.01?-10:f.trend<=-.003?-5:0;const a=c.map(x=>x.close);s+=Math.max(-5,Math.min(5,(ret(a,1)??0)*500));s+=Math.max(-8,Math.min(8,(ret(a,4)??0)*200));s+=Math.max(-6,Math.min(6,(ret(a,12)??0)*100));s+=Math.max(-6,Math.min(6,(ret(a,24)??0)*50));if(f.volumeRatio!==null)s+=f.volumeRatio>=2?10:f.volumeRatio>=1.3?7:f.volumeRatio>=1.05?3:f.volumeRatio<.7?-6:0;if(f.macdHist!==null)s+=f.macdHist>0?5:-5;if(f.rsi!==null)s+=f.rsi>=52&&f.rsi<=68?5:(f.rsi>=45&&f.rsi<=72?1:(f.rsi>78?-6:f.rsi<35?-5:0));if(f.atr!==null&&f.e200!==null&&f.e200>0&&f.atr/f.e200>.08)s-=5;return Math.round(Math.max(0,Math.min(100,s)))}
function mean(a:number[]){return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
async function main(){const end=new Date(),start=new Date(end);start.setUTCMonth(start.getUTCMonth()-MONTHS);const rows:any[]=[];for(const symbol of SYMBOLS){const c=await load(symbol,start.getTime(),end.getTime());console.log('[discovery] '+symbol+': '+c.length+' hourly candles');for(let i=220;i<c.length-24;i++){const w=c.slice(0,i+1),f=features(w),sc=score(f,w),entry=c[i].close;const r=(n:number)=>c[i+n].close/entry-1;rows.push({symbol,time:c[i].openTime,score:sc,r1:r(1),r4:r(4),r12:r(12),r24:r(24)})}}
const defs=[[0,39,'0-39'],[40,49,'40-49'],[50,59,'50-59'],[60,69,'60-69'],[70,79,'70-79'],[80,100,'80-100']];const byScore=defs.map(([lo,hi,bucket])=>{const x=rows.filter(r=>r.score>=lo&&r.score<=hi),n=x.length;return{bucket,signals:n,winRate4h:n?x.filter(r=>r.r4>COST).length/n:null,avg1h:mean(x.map(r=>r.r1)),avg4hNet:mean(x.map(r=>r.r4-COST)),avg12h:mean(x.map(r=>r.r12)),avg24h:mean(x.map(r=>r.r24))}});const high=rows.filter(r=>r.score>=70),low=rows.filter(r=>r.score<50);const report={report_name:'radar-crypto-discovery-1h',generated_at:new Date().toISOString(),data:{start:start.toISOString(),end:end.toISOString(),months:MONTHS,interval:'1h',symbols:SYMBOLS,total_observations:rows.length},methodology:{purpose:'Fast discovery screen for monotonic predictive structure, not a production backtest.',production_untouched:true,fee_bps:10,slippage_bps:5,score_note:'Candidate score reuses production indicator families with 1h-normalized horizons; it is research-only.'},by_score:byScore,comparison:{high_ge70:{signals:high.length,avg4hNet:mean(high.map(r=>r.r4-COST)),winRate4h:high.length?high.filter(r=>r.r4>COST).length/high.length:null},low_lt50:{signals:low.length,avg4hNet:mean(low.map(r=>r.r4-COST)),winRate4h:low.length?low.filter(r=>r.r4>COST).length/low.length:null}}};await fs.mkdir(REPORT_DIR,{recursive:true});await fs.writeFile(path.join(REPORT_DIR,'backtest-discovery-1h.json'),JSON.stringify(report,null,2)+'\n');await fs.writeFile(path.join(REPORT_DIR,'backtest-discovery-1h-by-score.csv'),['score_bucket,signals,win_rate_4h_net,avg_1h,avg_4h_net,avg_12h,avg_24h',...byScore.map(r=>[r.bucket,r.signals,r.winRate4h??'',r.avg1h??'',r.avg4hNet??'',r.avg12h??'',r.avg24h??''].join(','))].join('\n')+'\n');console.log('\n[discovery] SCORE SHAPE');for(const r of byScore)console.log(r.bucket+' n='+r.signals+' win4h_net='+(r.winRate4h===null?'N/A':(r.winRate4h*100).toFixed(1)+'%')+' avg4h_net='+(r.avg4hNet===null?'N/A':(r.avg4hNet*100).toFixed(3)+'%'));console.log('[discovery] high>=70 avg4h_net='+mean(high.map(r=>r.r4-COST))+' low<50 avg4h_net='+mean(low.map(r=>r.r4-COST)))}
main().catch(e=>{console.error('[discovery] Error:',e);process.exit(1)})